env:
  matrix:
    - PYVER="3.5"
    - PYVER="3.6"
    - PYVER="3.7"

sudo: false

os:
  - linux
  - osx

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
      mkdir $HOME/.matplotlib;
      echo "backend: TkAgg" >> $HOME/.matplotlib/matplotlibrc;
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
      sudo apt-get update;
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

install:
  - conda create -n pylbm_env python=$PYVER
  - source activate pylbm_env
  - conda install --file requirements-dev.txt -c conda-forge
  - conda install libgfortran
  - python --version
  - python setup.py install

script:
  - pytest --pylint --pylint-rcfile=.pyrcfile --pylint-error-types=EF pylbm
  - pytest --nbval notebooks
  - cd tests; pytest --mpl --h5diff -m "not slow" --cov=pylbm
after_success:
- codecov -e $PYVER